# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThinkFit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThinkFit
  pod 'IQKeyboardManagerSwift'
  #pod 'MMDrawerController'
  pod 'SideMenu', '~> 6.0'
  pod 'Alamofire'
  pod 'Kingfisher', '~> 5.0'
  pod 'DropDown'
  pod 'MBProgressHUD'
  pod 'GoogleSignIn'
  pod 'Firebase/Analytics'
  #pod 'Firebase/Auth'
  #pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'RealmSwift','5.0.0'
  pod "YoutubePlayer-in-WKWebView", "~> 0.2.0"
  pod 'Firebase/Crashlytics'
  pod 'SDWebImage'


  target 'ThinkFitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThinkFitUITests' do
    # Pods for testing
  end

end
